### ISSUE TITLE
Website URL in MELPA meta info is wrong

### ISSUE THREAD

**Issue by kamoii** [monkeyjunglejuice/matrix-emacs-theme#1]
![image](https://user-images.githubusercontent.com/52167401/147929803-db091dff-fdb6-411c-852c-01091f1fd625.png)
I think you meant `matrix-emacs-theme` not `matrix-theme-emacs`.

**Comment by monkeyjunglejuice** [comment]
@kamoii Thank you, I've messed this up in the commentary header. Should be updated with the correcct URL when Melpa pulls from origin/main.
