### ISSUE TITLE
Calendar weekend header misaligned

### ISSUE THREAD

**Issue by lbolla** [monkeyjunglejuice/matrix-emacs-theme#8]
The calendar weekday/weekend header is misaligned because the weekend days use `fixed-pitch-serif` face which may take more space than the default font. For the calendar header, it is important to use fonts with the same width for both weekdays and weekend days, to maintain the alignment with the underneath days.

See picture.
![Screenshot from 2022-01-06 10-42-52](https://user-images.githubusercontent.com/20991/148362864-375aad56-3d0d-4bff-af91-f7651774f620.png)

**Comment by lbolla** [comment]
PR submitted. Here is how it looks now:
![Screenshot from 2022-01-06 10-50-18](https://user-images.githubusercontent.com/20991/148363894-972a2e0d-b708-40f0-9659-803c034bc7d8.png)

**Comment by monkeyjunglejuice** [comment]
Thank you for pointing this out. When you compare a line of code and the same line of code commented, you may notice that they won't line up either. If `fixed-pitch-serif` hasn't been set, an arbitrary font will be chosen by Emacs from a list of alternatives, which seems to be the case here. Therefore I recommend to set the `fixed-pitch-serif` to a font that has the same width as the `default` font, but differs in some details. I've updated the README.

**Comment by lbolla** [comment]
Ah, very good point! Thanks, feel free to abandon this PR and close the ticket then.
